# Generated by Django 2.0.5 on 2019-12-02 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webanalysis', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accesslog',
            name='log_recording',
            field=models.DateTimeField(max_length=128, null=True),
        ),
    ]
